//! **Field-validation ground-truth records** for the kinematic decision
//! engine.
//!
//! The decision engine (`civicsense::decision::evaluate_safety`) is
//! zero-training, but its formal guarantees only transfer to a real
//! vehicle if it can be validated against **labelled field data**. The
//! README's "Data Collection for Evaluation" section and the research
//! paper's Section VI define the methodology; this module is the machine-
//! readable schema for a single recorded intersection approach.
//!
//! A record is a **synchronised snapshot** that maps 1:1 onto the engine's
//! inputs:
//!
//! - [`GroundTruthRecord::ego`] ↔ [`EgoState`](https://docs.rs) (`speed`,
//!   `distance_to_stop_line`).
//! - [`GroundTruthRecord::detections`] ↔ [`Detection`](https://docs.rs)
//!   (`bbox`, `class_id`, `speed`, `lateral_speed`, `distance`, `lane`,
//!   `turn_signal_active`).
//! - [`GroundTruthRecord::light`] and `time_to_red` ↔ `LightState` +
//!   `time_to_red`.
//!
//! Crucially the record also carries the **human-annotated expected
//! outcome** ([`GroundTruthOutcome`]) and the **expected warning level**
//! ([`ExpectedLevel`]), which is what lets us build a confusion matrix
//! over false positives / false negatives exactly as the paper specifies.
//!
//! ```text
//! mode            enum  ::  Manual | V2I | Simulator
//! light           enum  ::  Red | Yellow | Green | Unknown
//! lane_location   enum  ::  Same | Left | Right | Unknown
//! outcome         enum  ::  Stopped | Cleared | Blocked
//! expected_alerts enum      (bit-set across the alert types)
//! ```

use serde::{Deserialize, Serialize};

/// The minimum number of top-level (image-pair) expectation fields a
/// valid record must carry. Currently 6 (id, scenario, mode, light,
/// outcome, expected_level) plus the two nested structs.
const MIN_REQUIRED_FIELDS: usize = 6;

/// How a ground-truth record was produced. Different sources imply
/// different accuracy guarantees for the attached telemetry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DataSource {
    /// Annotated by a human from dashcam / smartphone footage.
    Manual,
    /// Pulled from a V2I / SPaT (signal-phase-and-timing) feed with a
    /// synchronized GNSS clock.
    V2i,
    /// Generated by a simulator (CARLA / SUMO) under controllable ground
    /// truth.
    Simulator,
}

/// The traffic-light phase at the stop line.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LightPhase {
    /// Light is red; the ego must stop.
    Red,
    /// Light is amber/yellow; time-to-red matters.
    Yellow,
    /// Light is green.
    Green,
    /// Phase could not be determined (vision-only worst-case).
    Unknown,
}

/// Lane location of a detected object relative to the ego.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LaneLocation {
    /// Same lane as the ego.
    Same,
    /// Lane to the immediate left.
    Left,
    /// Lane to the immediate right.
    Right,
    /// Unknown / unassigned.
    Unknown,
}

/// The human-annotated physical outcome of an intersection approach.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GroundTruthOutcome {
    /// The ego stopped before the stop line.
    Stopped,
    /// The ego cleared the intersection before the light changed.
    Cleared,
    /// The ego blocked the box / was trapped inside the intersection.
    Blocked,
}

/// The warning level a correct decision engine *should* have produced,
/// matching `civicsense::models::WarningLevel`, minus the `Safe` variant
/// which is implicit when nothing fires. Reusing the exact enum here keeps
/// the confusion-matrix comparison trivial.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExpectedLevel {
    /// A `Safe` / no-alert condition.
    Safe,
    /// A `Caution` advisory.
    Caution,
    /// A `Warning`.
    Warning,
    /// A `Critical` alert.
    Critical,
}

/// A single detected object inside a ground-truth record.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct GroundTruthDetection {
    /// Bounding box `(x_min, y_min, x_max, y_max)` in pixels.
    pub bbox: [f32; 4],
    /// The CivicSense class id (see [`crate::classes`]).
    pub class_id: usize,
    /// Longitudinal speed in m/s.
    pub speed: f32,
    /// Lateral speed in m/s (positive = right in image plane).
    pub lateral_speed: f32,
    /// Distance from ego front bumper to the object, metres.
    pub distance: f32,
    /// Lane location relative to the ego.
    pub lane: LaneLocation,
    /// Whether an amber turn signal was visible.
    pub turn_signal_active: bool,
}

/// The ego-vehicle telemetry, mirroring `civicsense::models::EgoState`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct GroundTruthEgo {
    /// Ego longitudinal speed, m/s.
    pub speed: f32,
    /// Distance from the ego's front bumper to the painted stop line, m.
    pub distance_to_stop_line: f32,
}

/// A full, validated intersection-approach ground-truth record.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct GroundTruthRecord {
    /// Stable, machine-readable identifier (e.g. `gt_000123`).
    pub id: String,
    /// Free-text scenario name for humans (`"Main & 5th, dry day"`).
    pub scenario: String,
    /// Where the record came from.
    pub mode: DataSource,
    /// Traffic-light phase.
    pub light: LightPhase,
    /// Seconds until the light turns red (valid when `Yellow`; often
    /// present for `Green` as the conservative time-to-red estimate).
    #[serde(default)]
    pub time_to_red: Option<f32>,
    /// Human-annotated physical outcome.
    pub outcome: GroundTruthOutcome,
    /// The warning level the engine should have produced.
    pub expected_level: ExpectedLevel,

    /// Ego telemetry.
    pub ego: GroundTruthEgo,
    /// Detected objects (may be empty for a clear approach).
    #[serde(default)]
    pub detections: Vec<GroundTruthDetection>,
}

impl GroundTruthRecord {
    /// Structural sanity check that all invariants hold.
    ///
    /// Returns `Ok(())` when the record is well-formed enough to feed a
    /// confusion-matrix evaluation; otherwise a `String` describing the
    /// first violated invariant.
    pub fn validate(&self) -> Result<(), String> {
        if self.id.is_empty() {
            return Err("`id` must not be empty".into());
        }
        if self.scenario.is_empty() {
            return Err("`scenario` must not be empty".into());
        }
        if self.ego.speed < 0.0 {
            return Err("`ego.speed` must be >= 0".into());
        }
        if self.ego.distance_to_stop_line < 0.0 {
            return Err("`ego.distance_to_stop_line` must be >= 0".into());
        }
        if self.light == LightPhase::Yellow && self.time_to_red.is_none() {
            return Err("yellow light must provide `time_to_red`".into());
        }
        if self.time_to_red.is_some_and(|t| t < 0.0) {
            return Err("`time_to_red` must be >= 0".into());
        }
        for d in &self.detections {
            if d.class_id >= crate::classes::NUM_CLASSES {
                return Err(format!("detection class_id {} out of range", d.class_id));
            }
            if d.distance < 0.0 || d.speed < 0.0 {
                return Err("detection `distance` and `speed` must be >= 0".into());
            }
        }
        Ok(())
    }
}

// ── Validation over a whole manifest / collection ─────────────────────

/// Result of validating a batch of ground-truth records.
#[derive(Debug, Default)]
pub struct ValidationReport {
    /// Number of records inspected.
    pub total: usize,
    /// Number of records that failed [`GroundTruthRecord::validate`].
    pub failed: usize,
    /// Identifiers of the failed records.
    pub failed_ids: Vec<String>,
}

/// Validates an iterator of records, returning a short [`ValidationReport`].
pub fn validate_records<'a, I>(records: I) -> ValidationReport
where
    I: IntoIterator<Item = &'a GroundTruthRecord>,
{
    let mut report = ValidationReport::default();
    for r in records {
        report.total += 1;
        if r.validate().is_err() {
            report.failed += 1;
            report.failed_ids.push(r.id.clone());
        }
    }
    report
}

// The constant guards against accidental removal of the schema's required
// fields; surfaced here rather than in code so doc readers can see it.
#[allow(dead_code)]
const _MIN_REQUIRED_FIELDS_GUARD: usize = MIN_REQUIRED_FIELDS;

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> GroundTruthRecord {
        GroundTruthRecord {
            id: "gt_000001".into(),
            scenario: "Main & 5th".into(),
            mode: DataSource::Manual,
            light: LightPhase::Yellow,
            time_to_red: Some(3.5),
            outcome: GroundTruthOutcome::Cleared,
            expected_level: ExpectedLevel::Safe,
            ego: GroundTruthEgo {
                speed: 12.0,
                distance_to_stop_line: 40.0,
            },
            detections: vec![],
        }
    }

    #[test]
    fn valid_record_passes() {
        assert_eq!(sample().validate(), Ok(()));
    }

    #[test]
    fn yellow_requires_time_to_red() {
        let mut r = sample();
        r.time_to_red = None;
        assert!(r.validate().is_err());
    }

    #[test]
    fn negative_speed_rejected() {
        let mut r = sample();
        r.ego.speed = -1.0;
        assert!(r.validate().is_err());
    }

    #[test]
    fn out_of_range_class_rejected() {
        let mut r = sample();
        r.detections = vec![GroundTruthDetection {
            bbox: [0.0, 0.0, 10.0, 10.0],
            class_id: 99,
            speed: 1.0,
            lateral_speed: 0.0,
            distance: 5.0,
            lane: LaneLocation::Same,
            turn_signal_active: false,
        }];
        assert!(r.validate().is_err());
    }

    #[test]
    fn report_counts_failures() {
        let good = sample();
        let mut bad = sample();
        bad.id = "gt_000002".into();
        bad.ego.speed = -3.0;
        let report = validate_records([&good, &bad]);
        assert_eq!(report.total, 2);
        assert_eq!(report.failed, 1);
        assert_eq!(report.failed_ids, vec!["gt_000002"]);
    }

    #[test]
    fn serde_roundtrip() {
        let r = sample();
        let json = serde_json::to_string(&r).unwrap();
        let back: GroundTruthRecord = serde_json::from_str(&json).unwrap();
        assert_eq!(r, back);
    }
}
